# Site title and description
title: EstateLawFAQs.com
description: Get answers to all of your estate planning questions. From estate law to probate, to finding an estate planning attorney, EstateLawFAQS.com has you covered.
lang: en

# Site base hostname & protocol, e.g. http://example.com
url: ""

# Site subpath, e.g. /blog
baseurl: ""

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink: /:title/

# Site logo # e.g. logo.png, upload logo image file to /uploads/ folder
logo:

navbar:
  sticky: true
  search: true

# Default author settings
author:
  name: Pete Seth
  title: Lead Developer
  avatar: avatar-tom.png

# Author settings, displayed on post and doc pages if front matter references author name e.g. author: peter
authors:
  john:
    name: John Brown
    title: Support
    avatar: avatar-john.png
  evan:
    name: Evan Wells
    title: Support
    avatar: avatar-evan.png
  sara:
    name: Sara Galen
    title: Lead Developer
    avatar: avatar-sara.png
  alex:
    name: Alex Koch
    title: Design Engineer
    avatar: avatar-alex.png
  daniel:
    name: Daniel Shultz
    title: Developer
    avatar: avatar-daniel.png
  tom:
    name: Tom Farrell
    title: Developer
    avatar: avatar-tom.png

# Default footer image settings
footer:
  copyright: Made by a dbg web co.

# Disqus comments shortname, requires Disqus account https://disqus.com/
disqus:
  shortname: # 1234

# Google analytics code, get your code here https://www.google.com/analytics/
google_analytics:

# Number of posts displayed on blog page
paginate: 10

# Blog path
paginate_path: "/blog/:num/"

# Path to post content assets directory i.e post images, pdfs etc
uploads: /uploads/

# Build settings
markdown: kramdown
highlighter: rouge

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-avatar

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

sass:
  style: compressed

collections:
  docs:
    output: true
  featured-faqs:
    output: false

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      layout: doc
